- app/build.gradle.kts
- app/src/main/res/values/styles.xml
Also fixed:
- TIQR-248: Fix kerning font
> TIQR-249: Fix pincode font

- .github/workflows/build.yml
- .github/workflows/release.yml
- .gitignore
- app/build.gradle.kts
Create a signed APK and app-bundle when a git-tag is set.
Use the git-tag name (vx.y.z) for the app version
> Auto build release

- app/build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
```
Update to Java 11
```
```
Use a newer Java version
```
> TIQR-298: Update to Java 11

- app/src/main/res/drawable/ic_identity_add.xml
- app/src/main/res/drawable/ic_identity_list.xml
- app/src/main/res/drawable/ic_info.xml
```
Update the icons in the eduID app to use a white foreground color. 
```
> Update eduID icons to white foreground

- app/src/debug/res/values/strings.xml
```
Change the name of the app in the phone's launcher so it's easier to have both debug and production version on one device.
```
> Show 'DEBUG' in app-name for debug-builds

- app/build.gradle.kts
- app/src/main/kotlin/nl/eduid/EduIdApplication.kt
- build.gradle.kts
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
```
Added missing dependency declaration in the version catalog of the app. Updating dependencies after core dependencies were updated.
Dependency resolution fix from Daniel.
```
```
After updating to the latest core dependency, the app needs to add a new library in the version catalog and also update dependencies.
```
```
```
```
```
> Fix dependencies update with @dzolnai

- app/src/main/kotlin/nl/eduid/EduIdApplication.kt
See https://github.com/Tiqr/tiqr-app-core-android/pull/66
> Update core, Bugfix tiqr 327 328

- .github/workflows/build.yml
- app/build.gradle.kts
```
This will create an regular and a debug APK for each PR, to install manualy on devices
```
> Build and store debug APK's

- .github/workflows/release.yml
```
Publish the signed app bundle to the internal track of the playstore.
```
```
Get rid of fastlane
```
> Publish releases to internal testing track

- .github/workflows/build.yml
```
Publish the nl.eduid.testing app to the internal test-track on google play, instead of the alfa track
```
> Publish to internal testing track

- app/src/main/res/values-nl/strings.xml
```
Translations were different in the android/ios/web app. Used the web-teksts when different
```
> Sync translations with iOS and web

- app/src/main/kotlin/nl/eduid/screens/homepage/HomePageWithAccountContent.kt
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values/strings.xml
```
Based upon user feedback, the pop-up after unauthenticated requests to the API was unclear.
```
> Update translations for starting oauth flow

- .github/sync.yaml
- .github/workflows/localicious.yaml
```
This wil create a PR in the github repo of the eduID iOS counterpart of this app, if the translation file was changed.
```
> Send updated translations to the iOS app as PR

- app/src/main/kotlin/nl/eduid/graphs/AuthGraph.kt
- app/src/main/kotlin/nl/eduid/graphs/MainGraph.kt
- app/src/main/kotlin/nl/eduid/graphs/Routes.kt
- app/src/main/kotlin/nl/eduid/screens/authorize/AuthenticationPinBiometricScreen.kt
- app/src/main/kotlin/nl/eduid/screens/authorize/EduIdAuthenticationViewModel.kt
- app/src/main/kotlin/nl/eduid/screens/onetimepassword/OneTimePasswordScreen.kt
- app/src/main/kotlin/nl/eduid/ui/PinInputField.kt
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values/strings.xml
- localizations.yaml
When there's no internet connection, we show a screen with a one-time password, which can be used to log in on the website
> TIQR-443: One time password screen

- app/src/main/kotlin/nl/eduid/flags/FeatureFlag.kt
- app/src/main/kotlin/nl/eduid/screens/personalinfo/PersonalInfoScreen.kt
- app/src/main/kotlin/nl/eduid/screens/personalinfo/PersonalInfoViewModel.kt
It is a core feature now, so no flag needed.
> TIQR-493: Fully remove iDIN / eIDAS feature flag

- app/src/main/kotlin/nl/eduid/MainComposeActivity.kt
- app/src/main/kotlin/nl/eduid/screens/scan/ScanScreen.kt
We don't support dark mode, so we need to set the status bar icons to be always dark colored
> TIQR-495: Fix status bar icon color

- app/src/main/kotlin/nl/eduid/di/api/EduIdApi.kt
- app/src/main/kotlin/nl/eduid/di/assist/DataAssistant.kt
- app/src/main/kotlin/nl/eduid/di/model/EduIdModels.kt
- app/src/main/kotlin/nl/eduid/di/model/ModelToState.kt
- app/src/main/kotlin/nl/eduid/graphs/MainGraph.kt
- app/src/main/kotlin/nl/eduid/graphs/Routes.kt
- app/src/main/kotlin/nl/eduid/screens/personalinfo/PersonalInfoData.kt
- app/src/main/kotlin/nl/eduid/screens/personalinfo/PersonalInfoRepository.kt
- app/src/main/kotlin/nl/eduid/screens/personalinfo/PersonalInfoScreen.kt
- app/src/main/kotlin/nl/eduid/screens/personalinfo/PersonalInfoViewModel.kt
- app/src/main/kotlin/nl/eduid/screens/personalinfo/banners/ControlCodeBanner.kt
- app/src/main/kotlin/nl/eduid/screens/personalinfo/banners/NotVerifiedBanner.kt
- app/src/main/kotlin/nl/eduid/screens/verifyidentity/VerifyIdentityScreen.kt
- app/src/main/kotlin/nl/eduid/screens/verifywithid/code/VerifyWithIdCodeScreen.kt
- app/src/main/kotlin/nl/eduid/screens/verifywithid/code/VerifyWithIdCodeViewModel.kt
- app/src/main/kotlin/nl/eduid/screens/verifywithid/input/VerifyWithIdInputScreen.kt
- app/src/main/kotlin/nl/eduid/screens/verifywithid/input/VerifyWithIdInputViewModel.kt
- app/src/main/kotlin/nl/eduid/ui/Buttons.kt
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values/strings.xml
- localizations.yaml
> TIQR-507: Fallback method code screen

- app/src/main/kotlin/nl/eduid/screens/verifywithid/code/VerifyWithIdCodeScreen.kt
> TIQR-507: Center link in screen

- app/src/main/kotlin/nl/eduid/ErrorData.kt
- app/src/main/kotlin/nl/eduid/screens/authorize/AuthenticationPinBiometricScreen.kt
> TIQR-520: Crash fixes based on Google Play reports

- app/build.gradle.kts
- app/src/main/kotlin/nl/eduid/MainComposeActivity.kt
- app/src/main/kotlin/nl/eduid/screens/homepage/HomePageWithAccountContent.kt
- gradle/libs.versions.toml
Testing can be enabled / disabled by tapping the "Your eduID app is ready for use" 5 times
> TIQR-514: Update notification for eduID

- app/build.gradle.kts
- app/src/main/kotlin/nl/eduid/di/api/EduIdApi.kt
- app/src/main/kotlin/nl/eduid/di/model/EduIdModels.kt
- app/src/main/kotlin/nl/eduid/di/module/EduIdModule.kt
- app/src/main/kotlin/nl/eduid/di/repository/EduIdRepository.kt
- app/src/main/kotlin/nl/eduid/flags/FeatureFlag.kt
- app/src/main/kotlin/nl/eduid/graphs/MainGraph.kt
- app/src/main/kotlin/nl/eduid/graphs/Routes.kt
- app/src/main/kotlin/nl/eduid/screens/emailcodeentry/EmailCodeEntryScreen.kt
- app/src/main/kotlin/nl/eduid/screens/emailcodeentry/EmailCodeEntryViewModel.kt
- app/src/main/kotlin/nl/eduid/screens/personalinfo/PersonalInfoViewModel.kt
- app/src/main/kotlin/nl/eduid/screens/requestiddetails/RequestEduIdFormScreen.kt
- app/src/main/kotlin/nl/eduid/screens/requestiddetails/RequestEduIdFormViewModel.kt
- app/src/main/kotlin/nl/eduid/screens/verifywithid/input/VerifyWithIdInputViewModel.kt
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values/strings.xml
- build.gradle.kts
- gradle/libs.versions.toml
- localizations.yaml
This still a work in progress since some transitions and edge cases are not handled yet, but it does contain the majority of the feature.
This PR also includes some tooling updates.
> TIQR-538: Register (login) with email code

- app/src/main/kotlin/nl/eduid/di/api/EduIdApi.kt
- app/src/main/kotlin/nl/eduid/di/assist/AuthenticationAssistant.kt
- app/src/main/kotlin/nl/eduid/di/model/EduIdModels.kt
- app/src/main/kotlin/nl/eduid/di/repository/EduIdRepository.kt
- app/src/main/kotlin/nl/eduid/graphs/Animation.kt
- app/src/main/kotlin/nl/eduid/graphs/MainGraph.kt
- app/src/main/kotlin/nl/eduid/graphs/Routes.kt
- app/src/main/kotlin/nl/eduid/screens/emailcodeentry/EmailCodeEntryScreen.kt
- app/src/main/kotlin/nl/eduid/screens/emailcodeentry/EmailCodeEntryViewModel.kt
- app/src/main/kotlin/nl/eduid/screens/emailcodeentry/RegistrationUrlContract.kt
- app/src/main/kotlin/nl/eduid/screens/oauth/OAuthScreen.kt
- app/src/main/kotlin/nl/eduid/screens/oauth/OAuthViewModel.kt
Added the feature to register with an email code.
> TIQR-538: Register with email code

- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
> Fix build error

- app/src/debug/AndroidManifest.xml
- app/src/main/kotlin/nl/eduid/CheckRecovery.kt
- app/src/main/kotlin/nl/eduid/di/module/EduIdModule.kt
- app/src/main/kotlin/nl/eduid/graphs/MainGraph.kt
- app/src/main/kotlin/nl/eduid/screens/biometric/EnableBiometricViewModel.kt
- app/src/main/kotlin/nl/eduid/screens/deeplinks/DeepLinkScreen.kt
- app/src/main/kotlin/nl/eduid/screens/deeplinks/DeepLinkViewModel.kt
- app/src/main/kotlin/nl/eduid/screens/homepage/HomePageViewModel.kt
- app/src/main/kotlin/nl/eduid/screens/pinsetup/RegistrationPinSetupViewModel.kt
- app/src/main/kotlin/nl/eduid/screens/scan/StatelessScanViewModel.kt
There were some cases where we should have shown the recovery phone number flow but we didn't. This PR fixes that.
In the cases where we don't show it, the website will.
> TIQR-552: Correctly detect if recovery flow is needed

- app/src/main/kotlin/nl/eduid/di/api/EduIdApi.kt
- app/src/main/kotlin/nl/eduid/di/model/EduIdModels.kt
- app/src/main/kotlin/nl/eduid/di/module/EduIdModule.kt
- app/src/main/kotlin/nl/eduid/di/repository/EduIdRepository.kt
- app/src/main/kotlin/nl/eduid/flags/FeatureFlag.kt
- app/src/main/kotlin/nl/eduid/graphs/MainGraph.kt
- app/src/main/kotlin/nl/eduid/graphs/Routes.kt
- app/src/main/kotlin/nl/eduid/screens/editemail/EditEmailScreen.kt
- app/src/main/kotlin/nl/eduid/screens/editemail/EditEmailViewModel.kt
- app/src/main/kotlin/nl/eduid/screens/emailcodeentry/EmailCodeEntryScreen.kt
- app/src/main/kotlin/nl/eduid/screens/emailcodeentry/EmailCodeEntryViewModel.kt
- app/src/main/kotlin/nl/eduid/screens/personalinfo/PersonalInfoRepository.kt
- app/src/main/kotlin/nl/eduid/screens/requestiddetails/RequestEduIdFormScreen.kt
- app/src/main/kotlin/nl/eduid/screens/requestiddetails/RequestEduIdFormViewModel.kt
- Login with email code is enabled by default
- Changing the email of the account now also needs to be verified with an email code
- Update password does not require a code confirmation, but requires opening a link from the email client
> TIQR-558: Change email with code flow, remove feature flag

- app/src/main/kotlin/nl/eduid/di/module/EduIdModule.kt
- app/src/main/kotlin/nl/eduid/graphs/ConfigurePassword.kt
- app/src/main/kotlin/nl/eduid/graphs/MainGraph.kt
- app/src/main/kotlin/nl/eduid/network/ApiError.kt
- app/src/main/kotlin/nl/eduid/network/ErrorConverter.kt
- app/src/main/kotlin/nl/eduid/screens/deleteaccountfirstconfirm/DeleteAccountFirstConfirmScreen.kt
- app/src/main/kotlin/nl/eduid/screens/editemail/EditEmailViewModel.kt
- app/src/main/kotlin/nl/eduid/screens/emailcodeentry/EmailCodeEntryScreen.kt
- app/src/main/kotlin/nl/eduid/screens/manageaccount/ManageAccountScreen.kt
- app/src/main/kotlin/nl/eduid/screens/resetpasswordconfirm/ResetPasswordConfirmViewModel.kt
Contains:
* TIQR-558: Better error messages in reset password screen
* TIQR-558: Fixed back navigation issues around password reset / add flows
* TIQR-568: Fixed HTML tags visible in UI in account delete screen
> TIQR-558: Improve error message, fix back navigation issues, HTML text display in delete account screen
